// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(ObjectivesContext))]
    [Migration("20171127024851_Added Tasks.")]
    partial class AddedTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Complete");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("WebAPI.Models.ObjectiveTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("ObjectiveId");

                    b.Property<int?>("ObjectiveTaskId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("ObjectiveTaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WebAPI.Models.ObjectiveTask", b =>
                {
                    b.HasOne("WebAPI.Models.Objective")
                        .WithMany("Tasks")
                        .HasForeignKey("ObjectiveId");

                    b.HasOne("WebAPI.Models.ObjectiveTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ObjectiveTaskId");
                });
#pragma warning restore 612, 618
        }
    }
}
