// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(ObjectivesContext))]
    [Migration("20171127040825_Change-name-toParentObjective")]
    partial class ChangenametoParentObjective
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Complete");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("WebAPI.Models.ObjectiveTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("ParentObjectiveId");

                    b.Property<int?>("ParentTaskId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ParentObjectiveId");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WebAPI.Models.ObjectiveTask", b =>
                {
                    b.HasOne("WebAPI.Models.Objective", "ParentObjective")
                        .WithMany("Tasks")
                        .HasForeignKey("ParentObjectiveId");

                    b.HasOne("WebAPI.Models.ObjectiveTask", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId");
                });
#pragma warning restore 612, 618
        }
    }
}
